### ISSUE TITLE
Voice is stripped from Ask

### ISSUE THREAD

**Issue by ShiftySituation** [tropo/tropo-webapi-csharp#40]
Using the Tropo class, create an Ask object and pass it into the Tropo class.  The Voice property of Ask is being stripped out and replaced with the global Voice that is a property of Tropo class.  This prevents the ability to mix languages.  Example; in english -> "press 1 for english".  in spanish -> "press 2 for spanish".

Looking at the code, the simple solution would probably be changing the Tropo.Ask(Ask ask) method to simply Serialize the Ask argument.  Maybe checking `if (ask.Voice == null) ask.Voice = this.Voice;`

**Comment by ShiftySituation** [comment]
I created a PR to fix this.

**Comment by frankmeten** [comment]
I approved your pr
