### ISSUE TITLE
NuGet package linking to wrong version of JSON.net

### ISSUE THREAD

**Issue by Adk77** [tropo/tropo-webapi-csharp#5]
If you install the NuGet Tropo package - it downloads and installs the latest NuGet version of JSON.net - however Tropo is looking for a specific version of JSON.Net that does not match the NuGet package.

To resolve this, I had to replace the JSON.net reference (newtonsoft) with the NuGet package and recompile.

**Comment by akalsey** [comment]
The latest commit should help that.
